---
# php variables
# php -r 'echo PHP_VERSION;' | cut -c 1,2,3

# mysql variables
mysql_otadmin_pass: "{{ randompass.stdout if randompass is not skipped else existingpass.stdout }}"
mysql_forgottenserver_pass: "{{ randompass.stdout if randompass is not skipped else existingpass.stdout }}"
