---

- name: create journal
  file:
    path: /var/log/journal
    state: directory
    owner: root
    group: systemd-journal
    mode: 02755

- name: create journald.conf.d
  file:
    path: /etc/systemd/journald.conf.d
    state: directory

- name: install journald.conf
  template:
    src: systemd/journald.conf
    dest: /etc/systemd/journald.conf.d/journald.conf
    owner: root
    group: root
    mode: 0644
  notify: restart systemd-journald

# systemd service setup
- name: create systemd system/user@.service.d
  file:
    path: /etc/systemd/system/user@.service.d
    state: directory

- name: installing systemd system/user@.service.d/accounting.conf
  template:
    src: systemd/user_service_accounting.conf
    dest: /etc/systemd/system/user@.service.d/accounting.conf
    owner: root
    group: root
    mode: 0644

- name: installing systemd system/user@.service.d/security.conf
  template:
    src: systemd/user_service_security.conf
    dest: /etc/systemd/system/user@.service.d/security.conf
    owner: root
    group: root
    mode: 0644